### ISSUE TITLE
Chrome Plugin always shows "failed to fetch" and does not function

### ISSUE THREAD

**Issue by finsterwalder** [passbolt/passbolt_api#482] opened 2023-04-13 16:59 UTC
## ISSUE NAME
* Passbolt Version: Passbolt hosted at https://cloud.passbolt.com/

### What you did
I start the Chrome Browser on my MacBook.
I click the Passbolt Extension Icon in the toolbar

### What happened
I get a message saying "failed to fetch" (see screenshot).
![Screenshot 2023-03-27 at 15 57 24](https://user-images.githubusercontent.com/206574/231829664-470c5f24-0937-4f31-892a-6dc77628e23c.png)

### What you expected to happen
A dialog where I can enter my password to log into my Passbolt account

I can then click on the Passbolt icon, which opens the passbolt website and starts a recovery (enter your email).
When I then click on the Icon again, I get a login dialog.

**Comment by Gamabunta57** [comment] 2023-04-18 16:02
Hello @finsterwalder 👋 !

Sorry to hear that you encounter issues with Passbolt. So for information a "failed to fetch" error happens when a request to a server is done and fails somehow (for many possible reasons).
I would like to know more about the situation so we can help better.

- do you still have the issue?
- is it a new installation of the extension (did you create a new browser profile or did you removed the extension at some point before reinstalling)?
- where you able to fully setup your account once with an extension or did you encounter an error during the process?
- are you using a proxy?

Also, if you still encounter this issue, I would be glad to have a look at the logs of the extension. Here's a procedure to get them if you want:
- Right click on the extension's icon in the toolbar
- Go on "Manage extension"
- In the appearing screen, enable the "developer mode" with the toggle button on the top right of the screen, if it's not already
- With the mode activated, you should be able to see in the extension details a panel "Inspect views"
- Click on "index.html" from that panel
- You should see a new window being opened with tabs.  Click on "Console" if you're not on this tab already
- Right click on one the displayed message you should see and choose "save as".

This will export all the messages displayed in this console in a file. If you can share it, it would help us a lot.

**Comment by finsterwalder** [comment] 2023-04-18 16:42
* I still have the issue.
* I did not create a new browser profile. It used to work and suddenly stopped. I uninstalled and reinstalled the plugin, but that did not help.
* I have a fully set up account.
* I'm not using a Proxy

I could share the log, but would not like to do it publicly. Is there a way how I can share it privately?

**Comment by Gamabunta57** [comment] 2023-04-24 10:04
Hey @finsterwalder 

Thank you for sending us the logs. 
Apparently, according to what it is said, the browser is blocking the request due to CORS restriction. The error I see is that there are pre-flight requests made to ensure requests can be made and on the server responses have no ACAO headers in it.

The thing is that there is no update on our side that should change that and I couldn't reproduce the issue as well.

Something could be set on your browser or machine that changes the behaviour. So I wonder, on your browser profile, do you have others extensions installed or do you have anti-viruses maybe ? Those can alter the browser behaviour and provokes that kind of errors (it could be something else of course, I'm still investigating on this one).

**Comment by finsterwalder** [comment] 2023-05-02 15:15
I'm using two plugins that could interfere with traffic (uBlock origin and I don't care about cookies), but passbolt.com is whitelisted in both of them.
I still see the problem, when I click the passbolt icon on the toolbar. I then click passbolt, which opens the passbolt signup page. I then click the toolbar icon again and get a login form in the opened windows. Clicking the icon once again also gives me the login inside of the addon dialog.
So for some reason the problem appears, when I try to access passbolt from an empty page or some other opened page. When I'm already on the cloud.passbolt.com page, it works. It's a little annoying, but usable...

**Comment by Gamabunta57** [comment] 2023-05-31 10:01
Hello @finsterwalder and sorry for the late answer.

I tried to reproduce the issue with the extensions installed. I couldn't. But, for the sake of making sure it's not them acting as a blocker, is it possible for you to try with these extension disabled (maybe you've already tried) and see if it behaves the same?

**Comment by finsterwalder** [comment] 2023-06-01 20:06
Even when all plugins bug Passbolt are disabled, it does not work.

**Comment by finsterwalder** [comment] 2023-06-02 13:41
Yes, I did that before (I think while plugins were enabled, though). I will try that without plugins and report back here...

**Comment by Gamabunta57** [comment] 2023-06-29 15:46
Hello 👋 

Do you have any news about this topic by any chance?

**Comment by finsterwalder** [comment] 2023-06-29 15:57
No update. I have my workaround and I'm currently not willing to invest any more time. If no other customers have this problem, then it may be something on my machine?!

**Comment by Gamabunta57** [comment] 2023-07-25 11:13
Ok. As there is no new users with this problem, I'll do as you said, closing the ticket.
Feel free of course to re-open it if you have any new elements on that topic.

**Closed by Gamabunta57** 2023-07-25 11:13 UTC
