### ISSUE TITLE
Import/Export in Community edition

### ISSUE THREAD

**Issue by twotwenty** [passbolt/passbolt_api#256] opened 2018-05-17 17:46 UTC
The pricing and pay core model is fine, import/export as a pay feature is more like a hostage situation.

Very excited for this project and sustainable open-source businesses like nextcloud but import/export being a pay feature is a major let down.

please do not hold demoing your software hostage with import 
and if I demo your software do not hold my data hostage without including a export feature. 
obviously I could write my own but that is not the point.

**Comment by stripthis** [comment] 2018-05-21 11:41
Closing this as this is not a bug. This has been discussed extensively on the community forum, where you can continue the discussion.
See. https://community.passbolt.com/t/as-a-logged-in-user-i-can-import-export-keepass-files/16/22
See. https://community.passbolt.com/t/how-are-features-determined-to-go-pro-vs-ce/652

**Closed by stripthis** 2018-05-21 11:41 UTC
