### ISSUE TITLE
As a user using passbolt on two computers I should be able to login on the second computer

### ISSUE THREAD

**Issue by allan-simon** [passbolt/passbolt_api#272] opened 2018-06-26 15:20 UTC
I'm using a self hosted instance of passbolt and when i install the plugin on my second computer , I'm stucked at the login step because it says

>  If you already have your own server running, please follow the setup link in your mailbox. 

but I have deleted this email month ago and I don't find anywhere in the interface where i can get it back
moreover directly connecting to the instance adress , it does not recognize that I have the plugin installed

**Comment by stripthis** [comment] 2018-06-28 09:09
Hi @allan-simon

> when i install the plugin on my second computer , I'm stucked
See. https://help.passbolt.com/faq/start/account-recover

> moreover directly connecting to the instance address , it does not recognize that I have the plugin installed
This is a separate issue. I'm not able to reproduce it. What is your operating system / browser version? What does your passbolt url instance look like?

**Comment by allan-simon** [comment] 2018-06-28 12:20
Thanks for the reply
> See. https://help.passbolt.com/faq/start/account-recover
ok got it, I searched the FAQ, but i was more looking for "how to use my account on two computers" kind of sentence.

> This is a separate issue. I'm not able to reproduce it. What is your operating system / browser version? What does your passbolt url instance look like?

ok do you want to me to create a separate issue ?
I'm on ubuntu 18.04 ,  firefox  60.0.2 , my instance look like "https://passbolt.mycompany.com"

**Comment by stripthis** [comment] 2018-07-09 03:13
Closing this, @allan-simon please create a separate issue if the browser extension is still not recognized.

**Closed by stripthis** 2018-07-09 03:13 UTC
