### ISSUE TITLE
As an administrator I should not be able to install passbolt on a hostname that is not RFC3986 compliant PASSBOLT-1943

### ISSUE THREAD

**Issue by Nidhoegger** [passbolt/passbolt_api#55] opened 2017-03-07 10:25 UTC
I am trying to install passbolt on a Debian 8 machine with nginx. I have done the installation twice now according to your docs. When I create the first account and browse to the URL given by the script, i get:

"Error! Something unexpected happened. The setup cannot be completed.".

The debug info is:

```
{
  "error": "settings could not be validated",
  "setup": {
    "stepId": "",
    "stepsHistory": "",
    "user": {
      "username": "<my_email@address>",
      "firstname": "Name",
      "lastname": "Lastname",
      "id": "<some id>"
    },
    "key": {},
    "settings": {
      "token": "",
      "domain": "",
      "securityToken": {},
      "armoredServerKey": ""
    }
  },
  "additional": {
    "settings": {
      "token": "<some token>",
      "domain": "http://<url>"
    },
    "user": {
      "username": "<my_email@address>",
      "firstname": "Name",
      "lastname": "Lastname",
      "id": "<some id>"
    }
  }
}
```

What make me fuzzy is that the settings part is completly empty. As this seems to occur in the plugin and the server seems to log nothing, i am completly lost here.

Infos:
OS: Debian 8
HTTP Server: Nginx
Specials: The network does NOT have internet access

**Comment by stripthis** [comment] 2017-03-07 10:27
Hi @Nidhoegger,

Can you tell us which domain you use locally? It is likely that this particular name is not validating. Getting this information (or something similar) will help us reproduce the issue.

Cheers,

**Comment by Nidhoegger** [comment] 2017-03-07 10:37
i access it using "http://test-passmgr" for testing purposes. It is resolvable via DNS and is entered in the /etc/hosts

**Comment by stripthis** [comment] 2017-03-07 10:41
We have an existing bug report for this, with domain "https://middle-earth" not working. I'm not sure if it doesn't work because there is a '-' in the domain name or because there is no '.something' (or both). We'll work on this, in the meantime try using passbolt.dev or similar as local domain name.

ref. PASSBOLT-1943

**Comment by Nidhoegger** [comment] 2017-03-07 10:46
Thanks for your help. Later I will change my hostname and report back!

**Comment by stripthis** [comment] 2017-03-07 11:01
Hi, I just tried with http://testpassmgr and it also creates an issue.

**Comment by Nidhoegger** [comment] 2017-03-07 11:26
I used our FQDN now (the server is locatable via test-passmrg.domain.local via our router) and this workds. So it needs to be a FQDN, not just a resolvable host.

**Comment by stripthis** [comment] 2017-03-07 11:30
To my knowledge it works with a resolvable host. It's just the format of the domain name (e.g. test-passmgr.domain.local validates, but test-passmgr does not).

**Comment by stripthis** [comment] 2017-05-24 05:45
- The passbolt server can not be installed if fullBaseUrl does not validate as url as per rfc7230 / rfc3986.
- The plugin domain check step crash with domain as middle-earth:4444. The error message should be better (e.g. this is not a valid domain).

Relevant:
validator.isURL in plugin Vendor/validator.js
Validation::url in API lib/Cake/Utility/Validation

**Comment by stripthis** [comment] 2017-08-18 09:36
Fixed in v.1.6.2

**Closed by stripthis** 2017-08-18 09:36 UTC
Labels: bug
