### ISSUE TITLE
Unexpected behaviour of empty PUT payload to /resources/resource_id.json

### ISSUE THREAD

**Issue by maretodoric** [passbolt/passbolt_api#493] opened 2023-08-18 13:31 UTC
## Unexpected behaviour of empty PUT payload to /resources/resource_id.json
* Passbolt Version: 4.1.2-1-ce
* Platform and Target:
-- Operating system: Ubuntu 20.04 LTS (Focal Fossa)
-- PHP: from docker image
-- Web server: from docker image
-- Database server: MariaDB 10.3
-- etc.: Using docker image : passbolt/passbolt:4.1.2-1-ce

### What you did
Accidentally discovered this, not sure if it's by design but doesn't look like it.
When you call `PUT /resources/{resource_id}.json` without any payload, it will change the password to json string:
```{"password": "<current_password>", "description": "<current_description>"}```

### What happened
Explained in `What you did`, but pretty much password is set to plaintext json string.

### What you expected to happen
Nothing should happen or http code above 400 should be issued? Or maybe even 500?

**Comment by cedricalfonsi** [comment] 2023-10-04 15:12
An internal ticket PB-25997 was created to assess the issue.

**Comment by ishanvyas22** [comment] 2023-10-16 10:41
Hey @maretodoric, we are not able to reproduce the issue you are having. Can you upgrade your passbolt app to latest version and see if you are still facing the problem?

**Comment by ishanvyas22** [comment] 2023-10-19 09:30
Closing this issue for now, if you are still facing the problem then feel free to reach out to our [community forum](https://community.passbolt.com/).

**Closed by ishanvyas22** 2023-10-19 09:30 UTC
