### ISSUE TITLE
After one entry is deleted, almost all the others disappear

### ISSUE THREAD

**Issue by AdrianNoss** [passbolt/passbolt_api#227] opened 2018-02-21 13:50 UTC
## ISSUE NAME
* Passbolt Version: 2.0.0-RC2 Commit Hash: ec2531801d2cfbf7f2b91df265a1c5d1ab7b2938
* Platform and Target:
-- Operating system: Debian 9.1
-- PHP: 7.0.27-0+deb9u1
-- Web server: Apache/2.4.25 (Debian)
-- Database server: 10.1.26-MariaDB-0+deb9u1
-- etc.: Fresh Passbolt install from git with one User and Group

### What you did
After creating some test entries, I deleted one. 

### What happened
In the web interface only a single entry is displayed, the rest has disappeared and the search function does not find them.

Neither a restart of the web server, nor a reboot of the host system solve the problem.

The remaining entries are only displayed again after a new entry has been created.

Before you delete an entry.
![screen_2018 02 21_12h59m59s_004_passbolt - open source password manager for teams - mozilla firefox](https://user-images.githubusercontent.com/18482965/36483321-1783371c-1716-11e8-8f1b-87e1f7a28038.png)

After you delete an entry.
![screen_2018 02 21_13h23m28s_005_passbolt - open source password manager for teams - mozilla firefox](https://user-images.githubusercontent.com/18482965/36483320-1765698a-1716-11e8-9e0e-5a7ddd3f479c.png)

**Comment by stripthis** [comment] 2018-02-21 15:49
hi @AdrianNoss, i'm not able to reproduce the issue, can you tell us more about:
- what kind of permissions you are setting on the deleted / not deleted passwords
- the group composition

Also could you check in the browser console to see if there is any error there?

**Comment by cedricalfonsi** [comment] 2018-02-21 15:54
@AdrianNoss Can you also provide browser console/network traces

**Comment by AdrianNoss** [comment] 2018-02-22 08:27
hi @cedricalfonsi. 

It does not always happen. This time I was able to delete several entries until the behavior occurred again.
The entries have no special permissions and the group only has reading rights

This is the browser console output from firefox (58.0.2) : 

- Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.
[Weitere Informationen]
 passbolt.bond-int.de

- Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/
toolbar.js:83:13

- Controller id is defined by options and by template, the template id will be overriden by the option id.
 passbolt.js:3:462288

- Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.
[Weitere Informationen]
 groups.json


The "Strict-Transport-Security" repeats for groups.json, resources and checkSession.json 

I use a self-signed certificate and the apache config from the debian 8 how to.

`
<IfModule mod_ssl.c>
    <VirtualHost _default_:443>
        ServerAdmin webmaster@localhost
        ServerName passbolt.bond-int.de
        DocumentRoot /var/www/passbolt_v2
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/apache.crt
        SSLCertificateKeyFile /etc/apache2/ssl/apache.key

        <Directory /var/www/passbolt_v2>
            Options FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        <FilesMatch “\.(php)$”>
            SSLOptions +StdEnvVars
        </FilesMatch>
        BrowserMatch “MSIE [2–6]” \
          nokeepalive ssl-unclean-shutdown \
          downgrade-1.0 force-response-1.0
        BrowserMatch “MSIE [17–9]” ssl-unclean-shutdown
    </VirtualHost>
</IfModule>
`

The Healthcheck is ok: 

---------------------------------------------------------------
 Healthcheck shell
---------------------------------------------------------------

 Environment

 [PASS] PHP version 7.0.27-0+deb9u1.
 [PASS] PCRE compiled with unicode support.
 [PASS] The temporary directory and its content are writable.
 [PASS] The public image directory and its content are writable.
 [PASS] The logs directory and its content are writable.
 [PASS] GD or Imagick extension is installed.
 [PASS] Intl extension is installed.
 [PASS] Mbstring extension is installed.

 Config files

 [PASS] The application config file is present
 [PASS] The passbolt config file is present

 Core config

 [FAIL] Debug mode is on.
  [HELP] Set debug = false; in config/passbolt.php
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Full base url is set to https://passbolt.bond-int.de
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [WARN] Using a self-signed certificate

 Database

 [PASS] The application is able to connect to the database
 [PASS] 18 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded.
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /var/www/.gnupg.
 [PASS] The directory /var/www/.gnupg containing the keyring is writable by the webserver user.
 [PASS] The public key file is defined in config/passbolt.php and readable.
 [PASS] The private key file is defined in config/passbolt.php and readable.
 [PASS] The server key fingerprint matches the one defined in config/passbolt.php.
 [PASS] The server public key defined in the config/passbolt.php is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt a message.
 [PASS] The public key can be used to sign a message.
 [PASS] The public key can be used to encrypt and sign a message.
 [PASS] The private key can be used to decrypt a message.
 [PASS] The private key can be used to decrypt and verify a message.
 [PASS] The public key can be used to verify a signature.

 Application configuration

 [PASS] Using latest passbolt version (2.0.0-rc2).
 [PASS] Passbolt is configured to force SSL use.
 [PASS] App.fullBaseUrl is set to HTTPS.
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

  1 error(s) found. Hang in there!

**Comment by cedricalfonsi** [comment] 2018-02-22 08:31
@AdrianNoss 
Thanks for the additional information. 
Would you be available for a call ? It would be interesting to dig into this issue with you

**Comment by AdrianNoss** [comment] 2018-02-22 11:08
@cedricalfonsi  
No problem. Just write me an email and i give you my contact infos. 
anoss(at)bond.de

**Comment by tbradsha** [comment] 2018-03-09 19:17
I am having the same issue on 2.0.0-rc2 using Chrome. This occurs after adding or deleting, and the full list doesn't reappear until I add or remove a password, though sometimes it requires multiple tries. There is always one entry in place, but after deleting/adding, the single entry may be different.

Platform and Target:
-- Operating system: Ubuntu 17.10
-- PHP: 7.1
-- Web server: Apache 2.4
-- Database server: MariaDB 10

One user, one group.

**Comment by stripthis** [comment] 2018-04-18 14:03
@kingfisher77  can you contact us at contact@passbolt.com with an example CSV file (like the same format but with obfuscated content) so that we can try to reproduce the issue. Thanks!

**Comment by stripthis** [comment] 2018-04-26 06:37
Fixed with 2.0.3

**Closed by stripthis** 2018-04-26 06:37 UTC
Labels: bug, can not reproduce, waiting for reporter feedback
