### ISSUE TITLE
Can't move to a new Server

### ISSUE THREAD

**Issue by el3ctrician** [passbolt/passbolt_api#167] opened 2017-09-07 09:41 UTC
Passbolt was installed on an old server under ISPConfig and we were planning to move it to a dedicated VPS so i followed this steps:
1. Export all GPG from old machine to the new one.
2. Copy SSL certs
3. Dump the database.
4. Backup the files.
5. Import everthing to the new server and configure a Vhost on apache2 running on Ubuntu 16.04 with php7.0-fpm 
i am facing several issues then:
1. application keeps locking for cache with the old directory structure -> work around : cache disabled
2. sessions can't be saved as they will be saved usng the cache -> work around : sessions handled by cake
3. no user can access and no usfeul debug information i see only this screen also with debug 1
![screenshot from 2017-09-07 11-25-02](https://user-images.githubusercontent.com/17578910/30156279-84535a0a-93bf-11e7-8ba8-997ab4d058b4.png)
 my http headers:
![screenshot from 2017-09-07 11-28-18](https://user-images.githubusercontent.com/17578910/30156410-e1588194-93bf-11e7-8449-b1874edfefd1.png)
my vhost config:
```
<VirtualHost *:80>
	ServerName XXXX
        ServerAdmin XXX@XXXXXX
        DocumentRoot /var/www/passbolt/public_html
        ErrorLog ${APACHE_LOG_DIR}/error-passbolt.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        #enable php-fpm
        <Directory /usr/lib/cgi-bin>
                Require all granted
        </Directory>
        
	<Directory /var/www/passbolt/public_html>
                AllowOverride All
        </Directory>
        
	<IfModule mod_fastcgi.c>
                AddHandler php7-fcgi .php
                Action php7-fcgi /php7-fcgi
                Alias /php7-fcgi /usr/lib/cgi-bin/php7-fcgi
                #FastCgiExternalServer /usr/lib/cgi-bin/php7-fcgi -socket /var/run/php/php7.0-fpm.sock -pass-header Authorization
        </IfModule>

</VirtualHost>
```
passbolt logs:
```
2017-09-06 17:35:55 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 17:36:05 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 17:36:08 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 17:36:10 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 17:38:24 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 17:38:26 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 17:49:52 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 18:01:35 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 18:01:37 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 18:08:55 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-06 18:08:57 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-07 07:34:18 Error: [ForbiddenException] You need to login to access this location
Request URL: /auth/checkSession.json
Stack Trace:
#0 /var/www/passbolt/public_html/lib/Cake/Controller/Component/AuthComponent.php(349): GpgAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/passbolt/public_html/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(AuthController))
#2 /var/www/passbolt/public_html/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(AuthController))
#3 /var/www/passbolt/public_html/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/passbolt/public_html/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/passbolt/public_html/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/passbolt/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#7 /var/www/passbolt/public_html/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2017-09-07 08:05:45 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-07 08:05:46 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-07 08:05:50 Warning: Warning (2): session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-07 08:43:11 Error: [BadRequestException] The authentication token is not valid.
Request URL: /setup/install/59b1052a-a57c-4e7e-be08-0b87c0a8006d/cd6070e9-3678-45ac-a1aa-268b4921df6c
Stack Trace:
#0 [internal function]: SetupController->install('59b1052a-a57c-4...', 'cd6070e9-3678-4...')
#1 /var/www/passbolt/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SetupController), Array)
#2 /var/www/passbolt/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/passbolt/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SetupController), Object(CakeRequest))
#4 /var/www/passbolt/public_html/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2017-09-07 08:47:02 Error: [ForbiddenException] You need to login to access this location
Request URL: /validation/User/edit.json
Stack Trace:
#0 /var/www/passbolt/public_html/lib/Cake/Controller/Component/AuthComponent.php(349): GpgAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/passbolt/public_html/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(ValidationRulesController))
#2 /var/www/passbolt/public_html/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(ValidationRulesController))
#3 /var/www/passbolt/public_html/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/passbolt/public_html/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/passbolt/public_html/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/passbolt/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ValidationRulesController), Object(CakeRequest))
#7 /var/www/passbolt/public_html/app/webroot/index.php(110): Dispatcher->disp
```
Any ideas how can i proceed ?

**Comment by stripthis** [comment] 2017-09-07 09:56
I would say you would want to clear the cache and do and set the session back to the default, since you seem to have an issue with that new specific session configuration.

Otherwise, probably better, you could do a fresh git clone, import the database backup, copy the profile picture, server key and reconfigure your app from there, so that you don't carry the old cache bagage.

On a side note this kind of request is out of scope for this repository issues, which should be about feature requests and bugs. If you require professional support for issues specific to your setup please contact us contact@passbolt.com. I'll leave the ticket open in case other users wants to pitch in.

**Comment by el3ctrician** [comment] 2017-09-07 12:26
Thanks for your answer, so i tried a fresh install in my server with only the gpg imported without importing the database, created a new admin account and tried to login with no luck, same error http:500 and the server is not respecting the auth protocol

**Comment by stripthis** [comment] 2017-09-07 12:39
Thanks @el3ctrician for providing more data, this seems more like a bug.

It seems to me that you maybe be facing the same problem than in #141, e.g. you do not have enough entropy on your virtual machine. Maybe try to install rng-tools or similar and see if this fix the issue? @kevinmuller is working on a fix for better decting entropy and gnupg version issues.

**Comment by el3ctrician** [comment] 2017-09-07 12:55
oki, installing rng-tools didn't fix the issue. Please tell me if you need any logs or keys or whatever ..

**Comment by kevinmuller** [comment] 2017-09-07 13:58
Hi @el3ctrician 

I am glad that we can work together on this. Being able to reproduce this issue has been quite a struggle.

I would need 2 things from you if possible:
- The GPG private key used for your server (if you can disclose it).
- The version of GPG that you are using (gpg --version)

It would be better that we communicate on 101 for the resolution.  Could you write to contact [at] passbolt [dot] com, we'll continue from there.

Thanks!
Kevin

**Comment by kevinmuller** [comment] 2017-09-08 17:44
Hi again @el3ctrician 

I have tried reproducing the issue. I ruled out that it can be due to GPG2, or that it is related to a lack of entropy. 

The only way this issue can be reproduced is when there is an error at the CakePHP side that generates a 500 error while authenticating, typically a cache issue. We have planned to work soon on improving the healthcheck to be able to detect this better.

I am closing this issue for now, as this is not a bug and is most likely related to a problem with your setup.

**Closed by kevinmuller** 2017-09-08 17:44 UTC
Labels: bug, installation issue

**Comment by Si-Richards** [comment] 2021-01-27 15:46
I've get this issue everytime my PHP packages are updated (Centos & via YUM).
Sent on a login loop because ownership of the session folder is stolen from NGINX and changed to Apache when PHP updates.

Simply change it back to NGINX and Job done.... 

Its annoying but not anything to do with Passbolt and more the environment.

**Comment by garrettboone** [comment] 2021-01-27 16:01
@Si-Richards Thanks for mentioning your scenario. Are you actually using Apache or was it just installed with PHP? I believe installing php-fpm would allow a non-Apache install.

**Comment by Si-Richards** [comment] 2021-01-28 09:10
> @Si-Richards Thanks for mentioning your scenario. Are you actually using Apache or was it just installed with PHP? I believe installing php-fpm would allow a non-Apache install.

Hi @garrettboone No worries at all. No i'm not using Apache for anything and the daemon is disabled. TBH my rationale was that when I setup the server in December 2017 I battled to get it up and running and abandoned Apache in favour of NGINX.

Your right i'm sure on php-fpm and I will take a look when I next upgrade/maintenance as it is in a production environment.

Off topic, the only reason I upgraded in last month was that Passbolt started to throw an Avatar based error message with Angular errors in the Chrome console but the update sorted that. 
Passbolt is still solid IMO.

**Comment by Si-Richards** [comment] 2021-01-28 09:33
This highlights the same issue with a 'FIX'

> Thanks again. In my specific case, it was the php-fpm package which simply expects php to be run with user apache and resets the folders owner on update. I fixed this by creating new session folders and declaring them in the config file. – Patrick R. May 24 '18 at 10:45

https://superuser.com/questions/1315718/owner-of-php-session-folder-keeps-changing
