### ISSUE TITLE
Installation stops on "Installing composer..."

### ISSUE THREAD

**Issue by ion-lane** [passbolt/passbolt_api#348] opened 2020-05-07 04:01 UTC
Hello,
I installing passbolt on this instruction https://help.passbolt.com/hosting/install/ce/debian-10-buster.html on Debian 10
Script stopped on this moment. Whats problem?
```
...
Setting up libcgi-pm-perl (4.40-1) ...
Setting up libhtml-template-perl (2.97-1) ...
Setting up mariadb-client-10.3 (1:10.3.22-0+deb10u1) ...
Setting up mariadb-server-10.3 (1:10.3.22-0+deb10u1) ...
Created symlink /etc/systemd/system/mysql.service → /lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/mysqld.service → /lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /lib/systemd/system/mariadb.service.
Setting up libcgi-fast-perl (1:2.13-1) ...
Setting up mariadb-server (1:10.3.22-0+deb10u1) ...
Processing triggers for systemd (241-7~deb10u3) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
=====================
Setting up mariadb...
=====================
Synchronizing state of php7.3-fpm.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable php7.3-fpm
gpg: WARNING: unsafe permissions on homedir '/home/www-data/.gnupg'
gpg: keybox '/home/www-data/.gnupg/pubring.kbx' created
gpg: /home/www-data/.gnupg/trustdb.gpg: trustdb created
Cloning into '/var/www/passbolt'...
remote: Enumerating objects: 891, done.
remote: Counting objects: 100% (891/891), done.
remote: Compressing objects: 100% (723/723), done.
remote: Total 891 (delta 310), reused 461 (delta 123), pack-reused 0
Receiving objects: 100% (891/891), 3.17 MiB | 3.17 MiB/s, done.
Resolving deltas: 100% (310/310), done.
======================
Installing composer...
======================
root@srvtest01:/tmp#
```

All script output [https://pastebin.com/KzMrJmKb](https://pastebin.com/KzMrJmKb)

**Comment by dlen** [comment] 2020-05-07 08:36
Hi @ion-lane!

Sadly I couldn't reproduce your issue. Could it be a network issue on your server or are you able to reproduce it consistently?

**Comment by ion-lane** [comment] 2020-05-07 10:40
I install through a proxy server.
The problem was that there was no access to the github.io and getcomposer.org sites. Access opened.
Now another problem.
```
...
======================
Installing composer...
======================
--2020-05-07 06:27:41--  https://getcomposer.org/installer
Connecting to 172.16.2.4:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 277120 (271K) [application/octet-stream]
Saving to: ‘composer-setup.php’

     0K .......... .......... .......... .......... .......... 18%  268K 1s
    50K .......... .......... .......... .......... .......... 36%  269K 1s
   100K .......... .......... .......... .......... .......... 55% 5.20M 0s
   150K .......... .......... .......... .......... .......... 73%  284K 0s
   200K .......... .......... .......... .......... .......... 92% 10.4M 0s
   250K .......... ..........                                 100% 7.07M=0.6s

2020-05-07 06:27:43 (478 KB/s) - ‘composer-setup.php’ saved [277120/277120]

All settings correct for using Composer
Downloading...
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Network is unreachable
Retrying...
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Network is unreachable
Retrying...
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Network is unreachable
The download failed repeatedly, aborting.
```

**Comment by stripthis** [comment] 2020-05-07 10:42
Hello @ion-lane  closing this issue as this seems to be an issue with your local environment and not a bug. Please open a new conversation or the forum: https://community.passbolt.com as this space is reserved for bugs. Thanks,

**Closed by stripthis** 2020-05-07 10:42 UTC
