### ISSUE TITLE
Styles files missing 

### ISSUE THREAD

**Issue by sijomc** [passbolt/passbolt_api#54] opened 2017-03-06 13:39 UTC
I am unable view the page due to lack of stile files. Where can I find style files? And how can I connect with existing installation? Please help me to make the installation woking.

Thanks in advance.

**Comment by stripthis** [comment] 2017-03-07 10:24
Hi @sijomc,

If the style files are missing it is very likely that the URLs are not resolving, so you have or more of the following issues:
- App.FullBaseUrl is not set in core.php
- URL rewriting is not enabled on your webserver

Please check out the following links fore more information: 
https://www.passbolt.com/help/tech/install
https://book.cakephp.org/2.0/en/console-and-shells/i18n-shell.html
https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908

Let us know if this helped or if this doesn't solve your issues. In the later case please provide more information about your environment and configuration.

Cheers,

**Comment by sijomc** [comment] 2017-03-10 11:15
Installed Passbolt on local Ubuntu 14.04 server.  Installation completed sucessfully added user details from browser. After all these, when trying to login using matser password, the page just hangs on "loading".  Have any idea on this? How can I fix it? 

Thanks in advance...

**Comment by kevinmuller** [comment] 2017-03-10 11:21
Hi @sijomc 
This is usually due to the App.fullBaseUrl parameter that is incorrect (see in app/Config/core.php).
Can you check that:
1) it is the same as the url you are using to access your app.
2) it uses the right url scheme. (http / https depending on your setup).

**Comment by sijomc** [comment] 2017-03-10 11:32
It was correct, the same URL, which I use in browser. I am using Nginx web server. Have any other redirection rules need to add?

**Comment by kevinmuller** [comment] 2017-03-10 15:41
Could you open the browser console and post a screenshot of what you see in the console tab, and in the network tab?
Thanks.

**Comment by sijomc** [comment] 2017-03-13 04:33
![image](https://cloud.githubusercontent.com/assets/16303174/23841550/1ea48c28-07d4-11e7-8358-ebf624cf45bd.png)
![image](https://cloud.githubusercontent.com/assets/16303174/23841570/3aaf5524-07d4-11e7-93f9-b0d5ca191536.png)

Please see screenshot...

**Comment by stripthis** [comment] 2017-04-21 09:05
Hi @sijomc , unfortunately we cannot reproduce the issue. There is something wrong with your local setup but we are not able to identify what with the current data. I suspect there is something wrong with you app.FullBaseUrl but it is hard to tell for sure.

**Closed by stripthis** 2017-04-21 09:05 UTC
Labels: installation issue

**Comment by tharok2090** [comment] 2017-04-21 11:42
Same problem here. This time with Centos but also using Nginx, so it might be something related to Nginx config... The site seems to work but any kind of linked resource is not loading at all (404).
