### ISSUE TITLE
Order by date doesn't work as expected

### ISSUE THREAD

**Issue by joberthel** [passbolt/passbolt_api#248] opened 2018-04-27 17:48 UTC
## ORDER BY DATE DOESN'T WORK AS EXPECTED
* Passbolt Version: 2.0.4-debian
* Platform and Target:
-- Database server: mysql:5.7
-- docker

### What you did
Click on any date column header under the "passwords" or "users" section. 
(eg. "Modified", "Last logged in")

### What happened
The rows get sort alphabetically by the text in the date columns.

<img width="175" alt="bildschirmfoto 2018-04-27 um 19 35 03" src="https://user-images.githubusercontent.com/34104366/39376970-ce3cfc70-4a53-11e8-9a23-dabe5705a43c.png">

### What you expected to happen
The rows should get sort by the timestamp.

**Comment by stripthis** [comment] 2018-04-27 17:49
Can confirm, thanks for the report @joberthel

**Comment by cedricalfonsi** [comment] 2018-04-30 09:04
I close this issue as it is a duplicate of a passbolt-appjs issue.
see : https://github.com/passbolt/passbolt-appjs/issues/1

**Closed by cedricalfonsi** 2018-04-30 09:04 UTC
Labels: bug
