### ISSUE TITLE
[FAIL] The private key cannot be used to decrypt a message | entropy score 3208 

### ISSUE THREAD

**Issue by Takalele** [passbolt/passbolt_api#213] opened 2018-01-07 11:45 UTC
Hi, 

i have followed the install instructions and all seems to be working(I can create user and store the passwords) but the healthcheck found one Error:

[FAIL] The private key cannot be used to decrypt a message

This this a cosmetic issue?

What is the impact of this message?

entropy score:
cat /proc/sys/kernel/random/entropy_avail
3208

healthcheck:

---------------------------------------------------------------
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
 Healthcheck shell
---------------------------------------------------------------

 Environment

 [PASS] PHP version 7.0.22-0ubuntu0.16.04.1
 [PASS] PCRE compiled with unicode support
 [PASS] The temporary directory and its content are writable
 [PASS] The public image directory and its content are writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://xxx
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [PASS] Not using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /home/www-data/.gnupg
 [PASS] The directory /home/www-data/.gnupg containing the keyring is writable by the user the webserver is running as.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The private key file is defined in app/config.php and readable.
 [PASS] The server key fingerprint matches the one defined in app/config.php.
 [PASS] The server key defined in the app/Config.php is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt and sign a message.
 [FAIL] The private key cannot be used to decrypt a message
  [HELP] Make sure that the server private key is valid and that there is no passphrase.

 Application configuration

 [PASS] Using latest passbolt version (1.6.5)
 [PASS] Passbolt is configured to force SSL use
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  1 error(s) found. Hang in there!

debug.log
2018-01-07 12:37:10 Notice: Notice (8): Use of undefined constant PROCESS_USER - assumed 'PROCESS_USER' in [/media/data/www/passbolt-xy/app/Console/Command/Task/HealthcheckTask.php, line 575]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
HealthcheckTask::assertGpg() - APP/Console/Command/Task/HealthcheckTask.php, line 575
include - APP/View/HealthCheck/index.ctp, line 78
View::_evaluate() - CORE/Cake/View/View.php, line 971
View::_render() - CORE/Cake/View/View.php, line 933
View::render() - CORE/Cake/View/View.php, line 473
Controller::render() - CORE/Cake/Controller/Controller.php, line 963
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 110

![passwolt1](https://user-images.githubusercontent.com/22237036/34649084-f49d5746-f3a7-11e7-8889-3bb0ac5889f3.jpg)
![passbolt2](https://user-images.githubusercontent.com/22237036/34649085-f6d805ba-f3a7-11e7-8caf-12ea1ab08a11.png)
![passbolt3](https://user-images.githubusercontent.com/22237036/34649087-f8457158-f3a7-11e7-9c81-4cf10aa74b93.png)

thank you in advance
BR
Takalele

**Comment by infectormp** [comment] 2018-01-07 15:29
duplicate of https://github.com/passbolt/passbolt_api/issues/212

**Comment by Takalele** [comment] 2018-01-08 11:27
Ive got the answer from here
https://community.passbolt.com/t/the-private-key-cannot-be-used-to-decrypt-a-message/211
this is a false positive in my case.

**Comment by stripthis** [comment] 2018-01-08 11:33
@Takalele it seems to me that there is a real issue actually.

E.g. it is possible that the key can be use to decrypt (that's what is done in gpgauth) but it cannot decrypt and verify the signature at the same time. We'll be rolling out more healtcheck with v2 to see what's going on. That would be helpful if you could try to check if your server key can be used to sign as we want to make this a requirement in the future.

**Comment by sidorovdmitry** [comment] 2018-01-10 12:40
Hi @stripthis . I can confirm the issue with private key. I have fresh installation on Ubuntu 16.04, step by step https://www.passbolt.com/help/tech/install

```Environment

 [PASS] PHP version 7.0.22-0ubuntu0.16.04.1
 [PASS] PCRE compiled with unicode support
 [PASS] The temporary directory and its content are writable
 [PASS] The public image directory and its content are writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [FAIL] Debug mode is on.
  [HELP] Set Configure::write('debug', 0); in app/Config/core.php
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://hidden-url
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [PASS] Not using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /home/passbolt/.gnupg
 [PASS] The directory /home/passbolt/.gnupg containing the keyring is writable by the user the webserver is running as.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The private key file is defined in app/config.php and readable.
 [PASS] The server key fingerprint matches the one defined in app/config.php.
 [PASS] The server key defined in the app/Config.php is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt and sign a message.
 [FAIL] The private key cannot be used to decrypt a message
  [HELP] Make sure that the server private key is valid and that there is no passphrase.

 Application configuration

 [PASS] Using latest passbolt version (1.6.5)
 [PASS] Passbolt is configured to force SSL use
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  2 error(s) found. Hang in there!

**Comment by stripthis** [comment] 2018-06-18 13:28
@JulianHochgesang  please open an issue on the community forum. Most likely your private key is not in the keyring.

**Closed by stripthis** 2018-06-18 13:28 UTC
Labels: bug

**Comment by stripthis** [comment] 2018-06-18 13:29
https://community.passbolt.com/c/installation-issues
