### ISSUE TITLE
Export 'ALL' passwords not working

### ISSUE THREAD

**Issue by Si-Richards** [passbolt/passbolt_api#330] opened 2019-09-09 10:21 UTC
Export 'ALL' passwords not working

* Passbolt Version: v2.11.0
* Platform and Target:
-- Operating system: CentOS Linux release 7.5.1804 (Core)
-- PHP: 7.0.30
-- Web server: Apache/2.4.6 (CentOS)
-- Database server: 5.5.60-MariaDB-wsrep MariaDB Server

### What you did
As admin user clicked on select all passwords then export.

### What happened
MSGBOX "Retrieving Passwords" flashes up and disappears.

### What you expected to happen
Should show dialog options for export options.

** Exporting single passwords or multiple is possible just not everything.

**Comment by stripthis** [comment] 2019-09-09 10:23
Thank you for the bug report. We'll investigate / try to reproduce and revert back to you.

**Comment by imrejonk** [comment] 2019-09-30 14:32
We are experiencing a similar issue when exporting more than 90 passwords. Exporting 90 passwords succeeds, exporting 91 passwords fails with the 'flashing' message box as described by @Si-Richards.

- Passbolt Version: v2.11.0 PRO
- Platform and Target:
  -- Operating system: Debian 10
  -- PHP: 7.3
  -- Web server: NGINX 1.14
  -- Database server: MariaDB 10.3

**Comment by s4ke** [comment] 2019-11-11 20:59
I am facing this exact same issue as well. Is there anything I can help to fix this?

**Comment by maulwurf87** [comment] 2019-11-11 22:15
I have the same issue but it starts over 2500. My Issue got closed from the bot instead of marked as a duplicate to this one, due to no reaction from anyone. Info's can be found here:

https://github.com/nextcloud/android/issues/4579#issue-499876764

**Comment by s4ke** [comment] 2019-11-12 16:28
After checking the logs of the passbolt container and not finding any request being sent to it, this seems to be an issue in the browser extension.

**Comment by s4ke** [comment] 2019-11-12 17:36
Okay, it seems like the request is garbled. My nginX proxy in front of the API has the following error:

```
<my_ip> - - [12/Nov/2019:18:34:26 +0100] "-" 000 0 "-" "-"
```

in access.log

The passbolt extension manages to get to this snippet:

```
  /**
   * Emit a message to the addon code
   * @param args
   */
  Port.prototype.emit = function() {
    var message = JSON.stringify(arguments);
    this._port.postMessage(message);
  };
```

but I do not get an answer back.

**Comment by s4ke** [comment] 2019-11-12 18:21
Okay, I found the issue. The request url is too long for firefox. If I manipulate the url manually, I get the same error in the nginx log.

One thing though: Why does passbolt_api answer on get requests?

https://<url>/resources.json?api-version=2&contain%5Bsecret%5D=1&filter%5Bhas-id%5D%5B%5D=5fa9d1a5-bfc6-4xxxxx

**Comment by s4ke** [comment] 2019-11-12 18:33
Okay, I debugged and generated the URL that the browser would be sending in python, and I successfully get 93 results.

As a sidenote: Why does the request work via get?

**Comment by s4ke** [comment] 2019-11-12 19:04
Okay, I got it working. If I change the batch size to 80, the request finishes. I will create a pull request to the browser extension regarding this.

**Comment by imrejonk** [comment] 2019-11-13 09:42
That's impressive @s4ke, you figured that out pretty quickly! Thanks for the PR. Let's see if @stripthis agrees :)

**Comment by s4ke** [comment] 2019-11-13 09:57
@imrejonk thanks, but all I did was just debug a little in Firefox and followed the request I should have been seeing in my nginx logs ;)

**Comment by cedricalfonsi** [comment] 2019-11-13 12:52
@s4ke Thanks for the investigation and the PR on the browser extension, it's very much appreciated. I'm closing this ticket and we'll continue the discussion on the browser extension repository [ticket](passbolt/passbolt_browser_extension/issues/87).

**Closed by cedricalfonsi** 2019-11-13 12:52 UTC
Labels: bug
