### ISSUE TITLE
Controller class AccountSettingsIndex could not be found - After upgrade

### ISSUE THREAD

**Issue by Si-Richards** [passbolt/passbolt_api#387] opened 2021-03-04 13:39 UTC
## Unable to Navigate to Administration Menu in GUI
* Passbolt Version: 3.0.1 Master
* Platform and Target:
-- Operating system: CentOS Linux release 7.9.2009
-- PHP: 7.2.34
-- Web server: nginx/1.19.7
-- Database server: 5.5.60-MariaDB

### What you did
Upgraded System as per instructions 
Passbolt 2.13.5 -> 3.0.1 master
PHP 7.0 -> 7.2
Composer 1.x -> 2 latest
OS update (yum update)

### What happened
When clicking Administration in the GUI i get a 500 error

### What you expected to happen
Should take you to the Admin menu

--------------------------------------------------------------------------------------------------------

**From Passbolt Error Log:**

> 2021-03-04 13:30:00 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /
> 
> 
> 2021-03-04 13:30:01 Error: [Cake\Routing\Exception\MissingControllerException] Controller class AccountSettingsIndex could not be found. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/Http/ControllerFactory.php:105)
> Request URL: /account/settings.json?api-version=v2
> 
> 
> 2021-03-04 13:30:20 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app/passwords
> 
> 
> 2021-03-04 13:30:24 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app/passwords
> 
> 
> 2021-03-04 13:30:47 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /
> 
> 
> 2021-03-04 13:30:47 Error: [Cake\Routing\Exception\MissingControllerException] Controller class AccountSettingsIndex could not be found. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/Http/ControllerFactory.php:105)
> Request URL: /account/settings.json?api-version=v2
> 
> 
> 2021-03-04 13:31:00 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app/administration/email-notification
> 
> 
> 2021-03-04 13:31:01 Error: [Cake\Routing\Exception\MissingControllerException] Controller class AccountSettingsIndex could not be found. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/Http/ControllerFactory.php:105)
> Request URL: /account/settings.json?api-version=v2
> 
> 
> 2021-03-04 13:31:05 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app/administration/
> 
> 
> 2021-03-04 13:31:05 Error: [Cake\Routing\Exception\MissingControllerException] Controller class AccountSettingsIndex could not be found. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/Http/ControllerFactory.php:105)
> Request URL: /account/settings.json?api-version=v2
> 
> 
> 2021-03-04 13:31:10 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app
> 
> 
> 2021-03-04 13:31:11 Error: [Cake\Routing\Exception\MissingControllerException] Controller class AccountSettingsIndex could not be found. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/Http/ControllerFactory.php:105)
> Request URL: /account/settings.json?api-version=v2
> 
> 
> 2021-03-04 13:31:11 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app/administration/
> 
> 
> 2021-03-04 13:31:11 Error: [Cake\Routing\Exception\MissingControllerException] Controller class AccountSettingsIndex could not be found. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/Http/ControllerFactory.php:105)
> Request URL: /account/settings.json?api-version=v2
> 
> 
> 2021-03-04 13:31:11 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app/administration/email-notification
> 
> 
> 2021-03-04 13:31:11 Error: [BadMethodCallException] Unknown method "getTheme" (/var/www/html/passbolt/vendor/cakephp/cakephp/src/ORM/Table.php:2654)
> Request URL: /app/passwords
> 
> 
> 2021-03-04 13:31:12 Error: [Cake\Routing\Exception\MissingControllerException] Controller class AccountSettingsIndex could not be found. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/Http/ControllerFactory.php:105)
> Request URL: /account/settings.json?api-version=v2

![Capture](https://user-images.githubusercontent.com/20224397/109972713-88423380-7cef-11eb-87b9-25f0d3865931.PNG)

**Comment by stripthis** [comment] 2021-03-04 14:06
Hello @Si-Richards, Passbolt v3 requires PHP 7.3 to work. Please install php 7.3, run a `composer update` and/or  `composer dump-autoload` to make sure the php class can be found.

I'm closing this ticket, as this looks like an installation issue and not a bug, feel free to open another issues under "installation issues" in the community forum: https://community.passbolt.com/

**Closed by stripthis** 2021-03-04 14:06 UTC
