### ISSUE TITLE
PassboltApiFetchError: Not Found since upgrade 4.10.0-1

### ISSUE THREAD

**Issue by grufocom** [passbolt/passbolt_api#527] opened 2024-11-25 10:43 UTC
* Passbolt Version:  passbolt-ce-server 4.10.0-1
* Platform and Target:
-- Operating system: ubuntu 22.04
-- PHP: 8.1.2
-- Web server: nginx 1.18.0
-- Database server: mariadb-server 10.6
-- etc.: go-passbolt-cli 0.1.9

### What you did
add a ressource via clit with go-passbolt-cli:
passbolt create resource -n TEST -p test1234

shared the ressource with go-passbolt-cli:
passbolt share resource -g GROUP-RESID --id RESID -t 15

opened web interface and tried to change something

### What happened
failed with "Not Found" error message:
![not_found_error_chrome_20241125-0](https://github.com/user-attachments/assets/9c961543-842d-4e6e-beb3-48b6082e0ac2)

browser debug console shows 404 on keys.json?...:
![not_found_error_chrome_20241125-3](https://github.com/user-attachments/assets/eb4653e2-f766-4e10-bd83-93f593d2a05b)

browser console error log:
[passbolt-1732527458874.log](https://github.com/user-attachments/files/17901503/passbolt-1732527458874.log)

### What you expected to happen
expected that my change got saved

**Comment by grufocom** [comment] 2024-11-25 10:54
Downgrade of server to version 4.9.1-1 did not solve the problem, maybe it is a browser plugin problem (version 4.10.0)...

**Comment by stripthis** [comment] 2024-11-25 13:00
Thanks for the report @grufocom we're investigating.

**Comment by grufocom** [comment] 2024-11-25 13:27
SELECT name, resource_type_id, metadata, metadata_key_type, metadata_key_id, created, modified FROM resources WHERE id = "557f2071-bb90-4a93-9ad4-c3cccd3675ba";
+-----------+--------------------------------------+----------+-------------------+-----------------+---------------------+---------------------+
| name      | resource_type_id                     | metadata | metadata_key_type | metadata_key_id | created             | modified            |
+-----------+--------------------------------------+----------+-------------------+-----------------+---------------------+---------------------+
| AX_123456 | dd1f723d-0d1e-513f-8218-4055dc0530d0 | NULL     | NULL              | NULL            | 2024-11-25 09:04:17 | 2024-11-25 09:04:17 |
+-----------+--------------------------------------+----------+-------------------+-----------------+---------------------+---------------------+
1 row in set (0,001 sec)

SELECT * from resource_types;
+--------------------------------------+---------------------------+---------------------------------+-------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+---------------------+---------------------+
| id                                   | slug                      | name                            | description                                                                   | definition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | deleted | created             | modified            |
+--------------------------------------+---------------------------+---------------------------------+-------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+---------------------+---------------------+
| 05ba5c75-504d-5ad6-819a-83af68867d86 | totp                      | Standalone TOTP                 | A resource with standalone TOTP fields.                                       | {"resource":{"type":"object","required":["name"],"properties":{"name":{"type":"string","maxLength":255},"uri":{"anyOf":[{"type":"string","maxLength":1024},{"type":"null"}]}}},"secret":{"type":"object","required":["totp"],"properties":{"totp":{"type":"object","required":["secret_key","digits","algorithm"],"properties":{"algorithm":{"type":"string","minLength":4,"maxLength":6},"secret_key":{"type":"string","maxLength":1024},"digits":{"type":"number","minimum":6,"exclusiveMaximum":9},"period":{"type":"number"}}}}}}                                                                                                                                                                                                                 | NULL    | 2023-05-17 06:14:57 | 2023-07-11 06:18:16 |
| 669f8c64-242a-59fb-92fc-81f660975fd3 | password-string           | Simple password                 | The original passbolt resource type, where the secret is a non empty string.  | {"resource":{"type":"object","required":["name"],"properties":{"name":{"type":"string","maxLength":255},"username":{"anyOf":[{"type":"string","maxLength":255},{"type":"null"}]},"uri":{"anyOf":[{"type":"string","maxLength":1024},{"type":"null"}]},"description":{"anyOf":[{"type":"string","maxLength":10000},{"type":"null"}]}}},"secret":{"type":"string","maxLength":4096}}                                                                                                                                                                                                                                                                                                                                                                    | NULL    | 2022-12-19 16:24:08 | 2022-12-19 16:24:08 |
| 7438294d-f71c-5164-ba95-d9e60e295564 | v5-default-with-totp      | Default resource type with TOTP | The new default resource type with a TOTP introduced with v5.                 | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | NULL    | 2024-11-22 07:59:19 | 2024-11-22 07:59:19 |
| 761e5863-e17e-5ded-b3c2-76ffd5d0a2dc | v5-password-string        | Simple Password (Deprecated)    | The original passbolt resource type, kept for backward compatibility reasons. | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | NULL    | 2024-11-22 07:59:19 | 2024-11-22 07:59:19 |
| 8cca88d9-a3f6-56df-b860-3ef08de5c5c4 | password-description-totp | Password, Description and TOTP  | A resource with encrypted password, description and TOTP fields.              | {"resource":{"type":"object","required":["name"],"properties":{"name":{"type":"string","maxLength":255},"username":{"anyOf":[{"type":"string","maxLength":255},{"type":"null"}]},"uri":{"anyOf":[{"type":"string","maxLength":1024},{"type":"null"}]}}},"secret":{"type":"object","required":["password","totp"],"properties":{"password":{"type":"string","maxLength":4096},"description":{"anyOf":[{"type":"string","maxLength":10000},{"type":"null"}]},"totp":{"type":"object","required":["secret_key","digits","algorithm"],"properties":{"algorithm":{"type":"string","minLength":4,"maxLength":6},"secret_key":{"type":"string","maxLength":1024},"digits":{"type":"number","minimum":6,"exclusiveMaximum":9},"period":{"type":"number"}}}}}} | NULL    | 2023-05-17 06:14:57 | 2023-07-11 06:18:16 |
| a28a04cd-6f53-518a-967c-9963bf9cec51 | password-and-description  | Password with description       | A resource with the password and the description encrypted.                   | {"resource":{"type":"object","required":["name"],"properties":{"name":{"type":"string","maxLength":255},"username":{"anyOf":[{"type":"string","maxLength":255},{"type":"null"}]},"uri":{"anyOf":[{"type":"string","maxLength":1024},{"type":"null"}]}}},"secret":{"type":"object","required":["password"],"properties":{"password":{"type":"string","maxLength":4096},"description":{"anyOf":[{"type":"string","maxLength":10000},{"type":"null"}]}}}}                                                                                                                                                                                                                                                                                                | NULL    | 2022-12-19 16:24:08 | 2022-12-19 16:24:08 |
| bb2280b5-c4d9-569c-9337-62b307f1139c | v5-totp-standalone        | Standalone TOTP                 | The new standalone TOTP resource type introduced with v5.                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | NULL    | 2024-11-22 07:59:19 | 2024-11-22 07:59:19 |
| dd1f723d-0d1e-513f-8218-4055dc0530d0 | v5-default                | Default resource type           | The new default resource type introduced with v5.                             | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | NULL    | 2024-11-22 07:59:19 | 2024-11-22 07:59:19 |
+--------------------------------------+---------------------------+---------------------------------+-------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+---------------------+---------------------+
8 rows in set (0,000 sec)

**Comment by stripthis** [comment] 2024-11-25 13:58
Data looks ok, did you enable the v5 flag in the config by any chance? I've tested the same scenario than you, I'm not able to reproduce the issue.

**Comment by stripthis** [comment] 2024-11-25 14:10
Can you reach to us at support@passbolt.com, we can investigate in a call that would be quicker I think.

**Comment by stripthis** [comment] 2024-11-25 15:55
We're able to reproduce the issue, it's specific to the go-passbolt-cli 0.1.9 version that contains a bug in resource type id selection, as well as an issue v4.10.0 that will be fixed with v4.10.1.

For now you will need to:
- manually change the resource types in DB to fix previously created resource with "v5-default" resource type
- update to the latest go passbolt cli version 

We can assist you with the same on support, I'm posting this in case someone else experience this.

**Closed as completed** 2024-12-12 10:42 UTC
Labels: bug
