### ISSUE TITLE
Share Filter List Crashes UI with letter A then T

### ISSUE THREAD

**Issue by cordeosdev** [passbolt/passbolt_api#450] opened 2022-10-22 16:54 UTC
Ok, its next to impossible to tell if this an API issue or JS front side extension issue, but...

We have been struggling with a strange UI crash for some time.  The share password popup crashes the interface when you type the characters "a" then "t" in succession.

We have lots of use groups and some of them are "ATB Users..." etc.  When we go to share a password and start typing in the filter box "a" then "t" the UI immediately flips to an all blank solid background color and stops there.  To recover you need to refresh the browser a couple of times and the interface comes back to the password list showing before you clicked 'Share'.

The "a" then "t" is the ONLY combination which seems to cause this.  We have tried every other pattern.

This issue is happening across different computers, different users, different browsers.  We have also confirmed this happens across our three different PASSBOLT installation including versions (api and ext) 3.1, 3.4 and we just upgraded one installation to 3.73 and the same issue occurs.

For reference, all three PASSBOLT installations were completed separately - but all share the same underlying platform (CentOS7, MariaDB 10.4, PHP7.3/7.4 with APACHE).

**Comment by garrettboone** [comment] 2022-10-22 17:03
I have seen something similar in a different app where the search results exhaust the PHP alloted memory. Are you getting PHP errors on the server side?

**Comment by cordeosdev** [comment] 2022-10-23 05:56
Wow... thats an excellent point and something we didnt look at.  Very possible, since the these "AT..." starting groups are also, coincidently, the largest number of groups, users and passwords.  THANKS!! will check on that right away and report back.

**Comment by cordeosdev** [comment] 2022-10-23 07:09
Unfortunately this doesnt seem to be the reason.  All three affected systems have large amounts of memory and we already checked Apache, PHP, MariaDB and Opcache memory settings.  Also, our largest groups and number of groups actually starts with "co..." and typing "c" then "o" filters normally in sharing.

Absolutely no errors are thrown on the server (httpd, php, passbolt, etc.).  So must be a client-side JS hiccup.

I guess nobody else is seeing this issue?  If so, must be our isolated "data" issue where one of the "at..." named groups has an overly long string length, illegal string character or something else which makes the JS puke when it attempts to filter on "a, t". 

Will have to endure being careful to type only "a" then scroll down the 30+ groups starting with A to select the right one.

Passbolt cake healthcheck and cake datachecks all pass 100%.
Testing reference version is CentOS7.9, Apache, MariaDB 10.4, PHP 7.4, Passbolt 3.7.3/3.7.3
*composer up to date and all packages updated
Same issue with  PHP7.3 Passbolt 3.1 and 3.4 installation (but same base OS config and similar databases seeds).

**Comment by garrettboone** [comment] 2022-10-23 12:03
The forum can help if it's not a bug, but getting more info from the extension logs will help determine this. https://community.passbolt.com/t/user-is-unable-to-fetch-the-passwords/4903/8?u=garrett this post has debug instructions. Maybe you can find errors on the client side with these steps.

**Comment by AnatomicJC** [comment] 2022-10-23 12:32
Garrett is right, if the UI is crashing, you should get informations in the browser extension debug logs. Please have a look at the link above about how to get them.
Additionaly, you can find also more logs on passbolt cakephp log files server side, located on `/var/www/passbolt/logs/error.log`.

Cheers,

**Comment by cordeosdev** [comment] 2022-11-06 11:48
Ok, we have scoured the servers up-down-around everywhere.  Nothing at all on the server side shows up out of the ordinary.  This would make sense because the glitch is almost instantaneous when you hit "t" after "a".   This really looks like problem with the extension.
Client side (extension debugging) reveals this exception thrown as soon as we tap the letter "t" after "a" in a sharing filter.

TypeError: this.state.autocompleteItems.map is not a function

data/js/dist/app.js:2 (anonymous function)
data/js/dist/app.js:2 (handleAutocompleteChange)
(self.dataChunkLoadingGlobal=self.dataChunkLoadingGlobal||[]).push([[216],{70597:(e,t,n)=>

**Comment by garrettboone** [comment] 2022-11-06 13:09
This is very helpful, thank you. 

https://github.com/passbolt/passbolt_styleguide/blob/1ce2f2cd889863b92cf96f659b35e8839f8b7032/src/react-extension/components/Common/Autocomplete/Autocomplete.js#L207

This might be the related line, and possibly should be `this.props.autocompleteItems.map` instead. But I still wouldn't understand why a specific letter combination would matter. Will be interesting to see what the team finds.

For the groups that start with AT, is there anything else peculiar about their names? Do they have non-text characters in them?

**Comment by garrettboone** [comment] 2022-11-07 14:14
I am able to reproduce it.

I created three new groups named like yours, and went to add a password to the first group and got the bug.

**Comment by garrettboone** [comment] 2022-11-07 14:39
I also just tested with NO groups that have `at` and the bug occurs then as well.

**Comment by cordeosdev** [comment] 2022-11-09 07:49
@garrettboone - thanks for confirmating our sanity.   This bug has been killing us for well over a year now and pretty hard to believe nobody else encountered or noticed this issue.  If we find time we will try to track down the JS code.

Is there a moderator who can move this issue to BROWSER EXTENSION?  
hesitant to open a duplicate issue.

**Comment by stripthis** [comment] 2022-11-09 08:17
Hello this is to confirm we can reproduce the issue and it will be fixed in the next release. No need to move the ticket, we have it on our radar. Thanks!

**Comment by cedricalfonsi** [comment] 2022-11-28 16:46
It was fixed with the browser extension [v3.8.0](https://help.passbolt.com/releases/ce/syria)

**Closed by cedricalfonsi** 2022-11-28 16:46 UTC
Labels: bug

**Comment by cordeosdev** [comment] 2023-02-15 02:56
Was this fix ever noted in any of the release notes?

**Comment by garrettboone** [comment] 2023-02-15 03:45
Yes, in the link provided above, PB-20978

Commit: https://github.com/passbolt/passbolt_styleguide/commit/c7ca1019c5c7de77b32f08fcd790b15b28f784e6
