### ISSUE TITLE
Re-Send Registration E-mail

### ISSUE THREAD

**Issue by CappelloA** [passbolt/passbolt_api#165] opened 2017-09-04 14:16 UTC
There no way in the users tab to re-send the registration mail to the passbolt platform.
I always have to delete and re-create the account.
If i try with the "old" mail that was sent, it says that it's expired.

**Comment by stripthis** [comment] 2017-09-05 07:34
Duplicate of https://github.com/passbolt/passbolt_api/issues/73

**Closed by stripthis** 2017-09-05 07:34 UTC
